// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEeGVzFhrTeVmZejDK2Vw098-WdJQU_1Y',
    appId: '1:39215040172:web:2efd902cdbd5fd63904109',
    messagingSenderId: '39215040172',
    projectId: 'gdtms-v2-app',
    authDomain: 'gdtms-v2-app.firebaseapp.com',
    storageBucket: 'gdtms-v2-app.firebasestorage.app',
    measurementId: 'G-DJ85BKKDWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCvOLYbV3toKI0XqxLAbDHv48G_W6LtQ',
    appId: '1:39215040172:android:a2981cb733554f92904109',
    messagingSenderId: '39215040172',
    projectId: 'gdtms-v2-app',
    storageBucket: 'gdtms-v2-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lfcInYp81tmtO-3xtxVbrEZ1an3Ym3I',
    appId: '1:39215040172:ios:58174f0ff9f54fc0904109',
    messagingSenderId: '39215040172',
    projectId: 'gdtms-v2-app',
    storageBucket: 'gdtms-v2-app.firebasestorage.app',
    iosBundleId: 'com.fsi.courier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9lfcInYp81tmtO-3xtxVbrEZ1an3Ym3I',
    appId: '1:39215040172:ios:58174f0ff9f54fc0904109',
    messagingSenderId: '39215040172',
    projectId: 'gdtms-v2-app',
    storageBucket: 'gdtms-v2-app.firebasestorage.app',
    iosBundleId: 'com.fsi.courier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEeGVzFhrTeVmZejDK2Vw098-WdJQU_1Y',
    appId: '1:39215040172:web:deb230016470bcdd904109',
    messagingSenderId: '39215040172',
    projectId: 'gdtms-v2-app',
    authDomain: 'gdtms-v2-app.firebaseapp.com',
    storageBucket: 'gdtms-v2-app.firebasestorage.app',
    measurementId: 'G-QHFYR9HYRN',
  );
}
