// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeE8ImlaT1daqSJKp0RNRG8cbWR3K4CA',
    appId: '1:722151057816:web:a361d445d6e0c9797163ed',
    messagingSenderId: '722151057816',
    projectId: 'itms-mobile-254ce',
    authDomain: 'itms-mobile-254ce.firebaseapp.com',
    storageBucket: 'itms-mobile-254ce.firebasestorage.app',
    measurementId: 'G-CNHRBRRE6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQH2jN_a3YnbvWczZiqZjd4blsZvPPHIQ',
    appId: '1:722151057816:android:575dc25f3aa0000b7163ed',
    messagingSenderId: '722151057816',
    projectId: 'itms-mobile-254ce',
    storageBucket: 'itms-mobile-254ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqThJgoP-5BTejf_U-aH_E5rE_MazXKnE',
    appId: '1:722151057816:ios:a81ac20aba7f8cd87163ed',
    messagingSenderId: '722151057816',
    projectId: 'itms-mobile-254ce',
    storageBucket: 'itms-mobile-254ce.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqThJgoP-5BTejf_U-aH_E5rE_MazXKnE',
    appId: '1:722151057816:ios:a81ac20aba7f8cd87163ed',
    messagingSenderId: '722151057816',
    projectId: 'itms-mobile-254ce',
    storageBucket: 'itms-mobile-254ce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXeE8ImlaT1daqSJKp0RNRG8cbWR3K4CA',
    appId: '1:722151057816:web:1866c6c756c1ff267163ed',
    messagingSenderId: '722151057816',
    projectId: 'itms-mobile-254ce',
    authDomain: 'itms-mobile-254ce.firebaseapp.com',
    storageBucket: 'itms-mobile-254ce.firebasestorage.app',
    measurementId: 'G-06MYK2XJZ3',
  );
}
